import * as React from "react";

export const About = () => {
  return (
    <div id="About-content"> 
      <p>
        ImmuneSpace blossomed from a shared idea that generating large amounts
        collaborative data, cross-center and cross-assay, to characterize the
        status of the immune system in diverse populations under normal
        conditions and in response to various stimuli would be a beneficial
        platform. The Human Immunology Project Consortium (
        <a
          href="https://www.immuneprofiling.org/hipc/page/show?pg=home"
          target="_blank">
          HIPC
        </a>
        ) program, an organization founded by the
        <a href="https://www.niaid.nih.gov/about/dait" target="_blank">
          {" "}
          NIAID-DAIT
        </a>
        , released ImmuneSpace in January 15, 2016.
      </p>
      <p>
        Since its release, ImmuneSpace has developed into powerful data
        management and analysis engine, where datasets can be easily explored
        and analyzed using state-of-the-art computational tools. ImmuneSpace
        takes advantage of the considerable infrastructure already developed
        through another HIPC platform,
        <a href="https://immport.niaid.nih.gov" target="_blank">
          {" "}
          ImmPort
        </a>
        , which serves as a repository of data generated by investigators funded
        by DAIT. Data are submitted by each HIPC center to ImmPort using a set
        of standardized data templates. Once ImmPort has made these data public
        through routine data releases, the data are transferred to ImmuneSpace
        where integrative modeling across various data types and HIPC centers
        are enabled.
      </p>
      <p>
        ImmuneSpace provides multiple ways to interact with, visualize, and
        analyze data. Each study contains tabs to view raw data, run common
        analyses, and look at custom reports. All the analyses make use of the R
        statistical language, leveraging
        <a href="http://rforge.net/Rserve/" target="_blank">
          {" "}
          Rserve{" "}
        </a>
        to improve performance and
        <a href="http://yihui.name/knitr/" target="_blank">
          {" "}
          knitr{" "}
        </a>
        to enable full reproducibility.
      </p>
      <img
        src="/AboutPage/images/dataflow.jpeg"
        padding-top="80%"
        width="40%"
        style={{ alignSelf: "center" }}
      />
      <p></p>
      <p>
        <b>Support:</b>
      </p>
      <ul>
        <li>
          Slack: The best way to connect with the ImmuneSpace team is via the
          ImmuneSpace{" "}
          <a href="https://immunespace.herokuapp.com/">slack workspace</a>
        </li>
        <li>
          Email: You can also reach the team at <b>immunespace@gmail.com</b>
        </li>
      </ul>
    </div>
  );
};
