import * as React from 'react';

// Styling imports
import './AboutPage.scss';

const AboutPage: React.FC = () => {

    const [divToShow, setDivToShow] = React.useState<string>("About");
    // --------- ABOUT -----------------
    const About: React.FC = () => { 
        return(
            <div id="About">
                <p>
                    ImmuneSpace blossomed from a shared idea that generating large 
                    amounts collaborative data, cross-center and cross-assay, 
                    to characterize the status of the immune system in diverse 
                    populations under normal conditions and in response to various 
                    stimuli would be a beneficial platform. The Human Immunology 
                    Project Consortium (
                    <a href="https://www.immuneprofiling.org/hipc/page/show?pg=home" target="_blank">HIPC</a>
                    ) program, an organization founded by the 
                    <a href="https://www.niaid.nih.gov/about/dait" target="_blank"> NIAID-DAIT</a>
                    , released ImmuneSpace in January 15, 2016. 
                </p>
                <p>
                    Since its release, ImmuneSpace has developed into powerful 
                    data management and analysis engine, where datasets can be 
                    easily explored and analyzed using state-of-the-art 
                    computational tools. ImmuneSpace takes advantage of the 
                    considerable infrastructure already developed through 
                    another HIPC platform, 
                    <a href="https://immport.niaid.nih.gov" target="_blank"> ImmPort</a>
                    , which serves as a repository 
                    of data generated by investigators funded by DAIT. Data are 
                    submitted by each HIPC center to ImmPort using a set of 
                    standardized data templates. Once ImmPort has made these data 
                    public through routine data releases, the data are transferred 
                    to ImmuneSpace where integrative modeling across various data 
                    types and HIPC centers are enabled.
                </p>
                <p>
                    ImmuneSpace provides multiple ways to interact with, visualize, 
                    and analyze data. Each study contains tabs to view raw data, 
                    run common analyses, and look at custom reports. All the 
                    analyses make use of the R statistical language, leveraging 
                    <a href="http://rforge.net/Rserve/" target="_blank"> Rserve </a> 
                    to improve performance and 
                    <a href="http://yihui.name/knitr/" target="_blank"> knitr </a>
                    to enable full reproducibility. 
                </p>
                <img src="/ResourcesPage/images/dataflow.jpeg"
                    padding-top="80%"
                    width="40%"
                    style={{alignSelf: 'center'}}
                    />
            </div>
        )
    }

    // --------- TOOLS -----------------
    const Tools: React.FC = () => { 
        return(
            <div id="Tools">
                <h3>Online Bioinformatics Tools Created by HIPC Members:</h3>
                <a href="http://icahn.mssm.edu/immuneregulation" target="_blank">ImmuneRegulation</a>
                <p>
                    Web platform that allows you to interactively explore the 
                    regulation of genes of interest by querying the regulation 
                    in the eQTL, Transcription Factor, and GQAS datasets. 
                </p>
                <a href="http://software.broadinstitute.org/gsea/msigdb/collection_details.jsp#C7" target="_blank">ImmuneSigDB</a> 
                <p>
                    A collection of Immune Signatures gene sets that represent cell types, states, 
                    and perturbations within the immune system developed by the Haining Lab.  
                </p>
                <a href="https://immcantation.readthedocs.io/en/stable/#" target="_blank">Immcantation</a>
                <p>
                    The Immcantation framework provide a start-to-finish analytical ecosystem for 
                    high-throughput AIRR-seq datasets. Beginning from raw reads, Python and R packages 
                    are provided for pre-processing, population structure determination, and repertoire analysis.
                </p>
                <a href="http://insilico.utulsa.edu/index.php/reliefseq/" target="_blank">ReliefSeq</a>
                <p>
                    Machine learning feature selection method for GWAS, RNA-Seq 
                    and other high-dimensional data sets able to identify 
                    genetic variables that influence continuous or dichotomous 
                    outcomes through interactions with other genetic variables. 
                </p>
            </div>
        )
    }

    // --------- NAVBAR -----------------
    // Use bootstrap in Navbar
    const Navbar: React.FC = () => { 
        
        const divInfo = [
            {
                id: "about",
                tag: "About",
                text: "About"
            },
            {
                id: "tools",
                tag: "Tools",
                text: "HIPC Tools",
            }
        ]

       
        const navBarElements = divInfo.map(function(el){
            const itemId = "navbar-link-" + el.id;
            const href = "#" + el.tag;

            const className = divToShow == el.tag ? " active" : "";
            return(
                <li id = {itemId} className = {className}>
                    <a href = {href} onClick={() => setDivToShow(el.tag)}>
                        {el.text}
                    </a>
                </li>
            )
        })

        return(
            <nav className="navbar navbar-default" style={{backgroundColor: 'white'}} >
                <div className="container-fluid">
                    <ul className="nav navbar-nav">
                        {navBarElements}
                    </ul>
                </div>
            </nav>
        )
    }

    // return
    return(
        <div>
            <Navbar/>
            { divToShow == "About" ? <About/> : null}
            { divToShow == "Tools" ? <Tools/> : null}
        </div>
    )
}

export const App: React.FC = () => {

    const filterBanner = document.getElementById('filter-banner')
    filterBanner.style.display = 'none'

    // Must return a React Fragment
    return <AboutPage/>
}