---
output: 
    html_document:
        self_contained: false
---

```{r setup, echo = FALSE}
library(knitr)
library(magrittr)
library(data.table)
getFileUrl <- function(filepath) {
  sub("/share/files", "/_webdav", filepath)
}
getFileLink <- function(filepath, filename) {
  paste0("<a href=\"", getFileUrl(filepath), "\">", filename, "</a>")
}
```

### Expression Sets
<div class="is2-downloads table-condensed">
```{r downloads, echo = FALSE}
files <- fread("/share/files/HIPC/IS2/@files/data/dataset_metadata.csv")
esets <- files[grepl("_eset\\.rds", dataset)]
eset_descriptions = c(
  all_noNorm_eset.rds = "All subjects, log2-normalized expression",
  all_noNorm_withResponse_eset.rds = "All subjects with immune response data, log2-normalized expression",
  all_norm_eset.rds = "All subjects, cross-study normalized and batch corrected expression",
  all_norm_withResponse_eset.rds = "All subjects with immune response data, cross-study normalized and batch corrected expression",
  young_noNorm_eset.rds = "Subjects age 18-50, log2-normalized expression",
  young_noNorm_withResponse_eset.rds = "Subjects age 18-50 with immune response data, log2-normalized expression",
  young_norm_eset.rds = "Subjects age 18-50, cross-study normalized and batch corrected expression", 
  young_norm_withResponse_eset.rds = "Subjects age 18-50 with immune response data, cross-study normalized and batch corrected expression",
  old_noNorm_eset.rds = "Subjects age 60-90, log2-normalized expression",
  old_noNorm_withResponse_eset.rds = "Subjects age 60-90 with immune response data, log2-normalized expression",
  old_norm_batchCorrectedFromYoung_eset.rds ="Subjects age 60-90, cross-study normalized and batch corrected using correction coefficients from young",
  old_norm_batchCorrectedFromYoung_withResponse_eset.rds = "Subjects age 60-90 with immune response data, cross-study normalized and batch corrected using correction coefficients from young",
  extendedOld_noNorm_eset.rds = "Subjects age 50-90, log2-normalized expression",
  extendedOld_noNorm_withResponse_eset.rds = "Subjects age 50-90 with immune response data, log2-normalized coutns",
  extendedOld_norm_batchCorrectedFromYoung_eset.rds = "Subjects age 50-90, log2-normalized counts",
  extendedOld_norm_batchCorrectedFromYoung_withResponse_eset.rds = "Subjects age 50-90 with immune response data, cross-study normalized and batch corrected using correction coefficients from young"
)
esets <- esets[, description := eset_descriptions[dataset]]

esets <- esets[, .(
  File = as.character(getFileLink(path, dataset)), 
  Description = as.character(description), 
  Participants = subjects, 
  Samples = samples, 
  Features = features
)]

knitr::kable(esets, escape = FALSE, format = "html")
```
</div>

### Other Datasets

<div class="is2-downloads table-condensed">
```{r immdata, echo = FALSE, warning=FALSE}
immdata <- files[dataset == "all_immdata_with_response.rds"]
immdata$description <- "Immune response data for all subjects where available"
immdata <- immdata[, .(
  File = as.character(getFileLink(path, dataset)), 
  Description = as.character(description), 
  Participants = subjects, 
  Samples = samples
)]
knitr::kable(immdata, escape = FALSE, format = "html")
```
</div>

<style>


  .is2-downloads td, .is2-downloads th {
    border: 1px solid #ddd;
    padding: 3px;
  }
  .is2-downloads tr:nth-child(even){background-color: #f2f2f2;}
  .is2-downloads tr:hover {background-color: #ddd;}
  .is2-downloads th {
    background-color: #255c97;
    text-align: left;
    color: white;
    font-size: 15px;
    font-weight: bold;
    padding: 3px;
  }

</style>
