
---
output: rmarkdown::html_document
---

***

## Transcriptional atlas of the human immune response to 13 vaccines reveals a common predictor of vaccine-induced immunity
* **Publication Date:** 
* **Journal:** Science Immunology
* **Authors:** The HIPC Signatures Project Team and the HIPC-II Consortium
* **Manuscript Link:** 
* **Contact Name:** 
* **Contact Email:** 
* **Abstract**   
    Systems biology approaches have been used to define molecular signatures and mechanisms of immunity to vaccination. However, most such studies have been done with single vaccines, and comparative analysis of the response to different vaccines is lacking. We integrated transcriptional data from 28 studies of 13 different vaccines, involving 820 healthy adults, and analyzed vaccination-induced signatures associated with the antibody response. Many shared transcriptional signatures of vaccination, including signatures of innate immunity occurring 1-3 days post-vaccination, as well as the cell cycle and plasma cell responses appearing 7 days post-vaccination, were observed. Despite the shared transcriptional response to most vaccines, at any given time point there was no evidence for a “universal signature” that could be used to predict the antibody response to all vaccines. However, accounting for the asynchronous nature of responses led to the identification of a time-adjusted signature that improved prediction antibody responses across vaccines. These results provide a transcriptional atlas of the human immune response to vaccination and define a common signature of vaccine- induced immunity.
* **Figures and code** 
    * [Main Report](/_webdav/HIPC/IS2/%40files/html_outputs/temporal.html){target="_blank"}
    * Code and output for [Figure 5](/_webdav/HIPC/IS2/%40files/html_outputs/temporal_figure_5.html)
