## Creation of normalized expression matrices from raw data for all cohorts

### Report generated by `r labkey.user.email`

```{r knitr-opts, echo=FALSE}
library(knitr)
opts_chunk$set(message=FALSE)
opts_chunk$set(cache.path=paste(labkey.file.root, "cache/expression_matrix_creation/", sep="/"), cache=FALSE)
```

```{r libs, cache=FALSE}
library(data.table)
library(GEOquery)
library(Rlabkey)
```

```{r queries, cache=TRUE}
GEF <- data.table(labkey.selectRows(labkey.url.base, labkey.url.path, "study", "gene_expression_files", colNameOpt="rname"))
bs_filter <- makeFilter(c("biosample_accession", "IN", paste0(unique(GEF$biosample_accession), collapse=";")))

bs2es <- data.table(labkey.selectRows(labkey.url.base, labkey.url.path, "immport", "biosample_2_expsample", colFilter=bs_filter, colNameOpt="rname"))
es_filter <- makeFilter(c("expsample_accession", "IN", paste0(unique(bs2es$expsample_accession), collapse=";")))
es <- data.table(labkey.selectRows(labkey.url.base, labkey.url.path, "immport", "expsample", colFilter=es_filter, colNameOpt="rname"))

pdata <- merge(es, bs2es, by="expsample_accession")
pdata <- merge(pdata, GEF, by="biosample_accession")

serie <- gsub("\\..*", "", unique(GEF$file_info_name))
eset <- getGEO(serie)[[1]]
f2g <- data.table(fData(eset))
f2g <- f2g[, list(ID, Symbol)]
setnames(f2g, colnames(f2g), c("feature_id", "gene_symbol"))

pdata <- pdata[, list(biosample_accession, description.x, subject_accession, study_time_collected, arm_accession, arm_name)]
setnames(pdata, "description.x", "GEO")
```

### Write files to disk
```{r write-files, cache=TRUE, dependson="queries"}
f2g_name <- "HT12_V3.tsv"
arms <- unique(pdata$arm_accession)
nEM <- length(arms)
GEM <- vector('list', nEM)
for(idx in 1:nEM){
  sspd <- pdata[arm_accession == arms[idx]]
  sspd <- sspd[ order(subject_accession, study_time_collected)]
  exprs <- data.table(exprs(eset)[, sspd$GEO])
  setnames(exprs, colnames(exprs), sspd[ match(colnames(exprs), GEO), biosample_accession])
  matdescr <- unique(pdata[arm_accession==arms[idx], arm_name])
  matname <- tolower(paste0("exprs_matrix_", gsub("\\s", "_", matdescr), ".tsv"))
  filename <- file.path(labkey.file.root, "analysis/exprs_matrices", matname)
  GEM[[idx]] <- data.table(biosample_accession = colnames(exprs), expression_matrix_accession = paste0("EM00", 10+idx), matrix_description = matdescr, file_info_name = matname, reagent_manufacturer = "Illumina", feature_mapping_file = f2g_name)
  exprs <- exprs[, feature_id := rownames(exprs(eset))]
  write.table(exprs, file=filename, sep="\t", quote=FALSE, row.names=FALSE)
}
write.table(f2g, file=file.path(labkey.file.root, "analysis/features2genes", f2g_name), row.names=FALSE)
```

```{r create-GEM, cache=TRUE, dependson="write-files"}
GEM <- rbindlist(GEM)
GEM <- merge(GEM, pdata, by="biosample_accession")
setnames(GEM, c("study_time_collected"), c("study_time_reported"))
GEM <- GEM[, list(subject_accession, biosample_accession, study_time_reported, expression_matrix_accession, matrix_description, file_info_name, feature_mapping_file, reagent_manufacturer, arm_name)]
GEM <- GEM[, SequenceNum := study_time_reported]
```

```{r query-GEM, cache=TRUE, dependson="create-GEM"}
bs_filter <- makeFilter(c("biosample_accession", "IN", paste0(GEM$biosample_accession, collapse=";")))
exist <- data.table(labkey.selectRows(labkey.url.base, labkey.url.path, "study", "gene_expression_matrices", colFilter = bs_filter, colNameOpt = "rname"))
```

### Insert rows into gene_expression_matrices 
```{r add-rows}
toImport <- GEM[!(biosample_accession %in% exist$biosample_accession)]
if(nrow(toImport) > 0){
	imported <- labkey.importRows(labkey.url.base, labkey.url.path, "study", "gene_expression_matrices", toImport = toImport)
}
```
