```{r knitr-options, echo=FALSE, eval=TRUE, cache=FALSE}
library(knitr)
opts_chunk$set(echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE, error=TRUE, dev="png", fig.width=6, fig.height=4, dpi=100, autodep=FALSE)
opts_chunk$set(cache.path=paste(labkey.file.root, "cache/pubmed_report_cache/", sep="/"), cache=TRUE)
options(width=80)
```
```{r load-required-packages, cache=FALSE}
# Required librairies
library(Rlabkey)
library(rentrez)
```

```{r filter}
study_acc <- gsub(".*/", "", gsub("/@files", "", labkey.file.root))

dat <- labkey.data
ds_pubmed <- dat[dat$study_accession == study_acc, ]
```

```{r get-pubmed-info, dependson="filter"}
loaded <- labkey.selectRows(labkey.url.base, "/Shared/", "lists", "loaded_studies", colNameOpt="rname")


get_reference <- function(id, related=FALSE){
   x <- entrez_summary(db="pubmed", id=id)
   reference <- paste(paste(x$AuthorList,collapse=", "), ". ", x$Title, " <i>", x$Source, "</i> ", x$Volume, "(", x$Issue, "), ", x$PubDate, ".", sep="")
   pubmed_link <- paste0("<a href='http://www.ncbi.nlm.nih.gov/pubmed/", id,"' target='_blank'>", "PMID:", id,"</a>")
   if(related){
    SDY <- as.character(dat[ dat$pubmed_id == id, "study_accession"])
    SDY <- SDY[SDY %in% loaded$study_accession]
    if(length(SDY)>0){
      SDY <- paste0("  [<a href='https://www.immunespace.org/project/Studies/", SDY ,"/begin.view?' target='_blank' title='Study ", SDY, " on ImmuneSpace'><b>",SDY,"</b></a>] ")
      pubmed_link <- paste(pubmed_link, SDY)
    }
   }
   return(paste(reference, pubmed_link))
}

# Update every month
id <- ds_pubmed$pubmed_id
id <- id[id != "PMC"]
if(length(id) ==0){
   citationtxt <- "No article references (PMIDs) could be found for this study. If you think this is an error, please post a message on the <a href='https://www.immunespace.org/project/home/support/begin.view', target='_blank'>support board</a> and the ImmuneSpace team will update this information as soon as possible."
} else{
  study_citation <- lapply(id, get_reference)
  pubmed_list <- entrez_link(db="all", id=id, dbfrom="pubmed")
  url_citedin <- paste0("http://www.ncbi.nlm.nih.gov/pubmed?linkname=pubmed_pubmed_citedin&from_uid=", id)
 
  citationtxt <- paste0("The above study is based on the following article(s):",
                        "\n", "<ul><li>", paste(study_citation, collapse="</li><br><li>"),  "</li></ul>",
                        "\n", "The article has <a href=", url_citedin, "target='_blank'>",
                        length(pubmed_list$pubmed_pubmed_citedin), "citations</a> in pubmed central.")
}
```

`r citationtxt`


```{r list-related-articles, results='asis', dependson="get-pubmed-info"}
if(length(id) ==0){
   relatedtxt <- " "
} else{
  cat("<h3> Related articles in PubMed are listed below: </h3>\n")
  res <- lapply(pubmed_list$pubmed_pubmed[-1][1:5], get_reference, related=TRUE)
  for(i in 1:5)
    {
    cat(paste0(i,". ", res[i],"\n"))
    }
  url_related <- paste0("http://www.ncbi.nlm.nih.gov/pubmed?linkname=pubmed_pubmed&from_uid=", ds_pubmed$pubmed_id)
  relatedtxt <- paste0("Click <a href=", url_related, "target='_blank'>here</a> for more suggestions.")
}
```

`r relatedtxt`
