# Creation of raw and normalized expression matrices from raw data.

### Report generated by `r labkey.user.email`

```{r knitr-options, echo=FALSE, cache=FALSE}
library(knitr)
opts_chunk$set(echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE, error=TRUE)
opts_chunk$set(cache=FALSE, cache.path=paste(labkey.file.root, "cache/expression_matrix_creation/", sep="/"))
options(width=80)
```

```{r load-required-packages, cache=FALSE}
library(data.table)
library(Rlabkey)
library(lumi)
```

## Merge all mapping information
```{r all, cache=TRUE}
ds_GE_files <- labkey.selectRows(baseUrl = labkey.url.base, folderPath = labkey.url.path, schemaName = "study", queryName = "gene_expression_files", colNameOpt = "rname")
dt_GE_files <- data.table(ds_GE_files)
biosamples_filter <- paste(unique(dt_GE_files$biosample_accession), collapse=";")

ds_exp_2_bio <- labkey.selectRows(baseUrl = labkey.url.base, folderPath = labkey.url.path,  schemaName = "immport", queryName = "biosample_2_expsample", colFilter = makeFilter(c("biosample_accession", "IN", biosamples_filter)), colNameOpt = "rname")
dt_exp_2_bio <- data.table(ds_exp_2_bio)
expsamples_acc_filter <- paste(dt_exp_2_bio$expsample_accession, collapse=";")

ds_expsamples <- labkey.selectRows(baseUrl = labkey.url.base, folderPath = labkey.url.path, schemaName = "immport", queryName = "expsample", colFilter = makeFilter(c("expsample_accession", "IN", expsamples_acc_filter)), colNameOpt = "rname")
dt_expsamples <- data.table(ds_expsamples)

#add biosample to expsample descr
dt_expsamples <- dt_expsamples[, biosample_accession:=dt_exp_2_bio[ match(dt_expsamples$expsample_accession, expsample_accession), biosample_accession]]
#add expsample descr to phenodata
expsample_descr <- dt_expsamples[match(dt_GE_files$biosample_accession, biosample_accession), description]
cnames <- paste0(gsub(";.*=", "_", gsub(".*ChipID=", "", expsample_descr)), ".AVG_Signal")

dt_GE_files <- dt_GE_files[, expr_col:=cnames]
dt_no_norm <- dt_GE_files[file_info_name=="XWAN_H12_SAMPLE_PROBE_PROFILE_NO_NORM_122211.txt",]
```

## Get expression values from file
```{r read-files, cache=TRUE, dependson="all"}
file <- paste(labkey.file.root, "rawdata/gene_expression", unique(dt_no_norm$file_info_name), sep="/")
xwan <- fread(file)

exprs_no_norm <- as.matrix(xwan[, dt_no_norm[,expr_col], with=FALSE])
colnames(exprs_no_norm) <- dt_no_norm[,biosample_accession]
rownames(exprs_no_norm) <- xwan$PROBE_ID
```

## create eset
```{r eset-creation, cache=TRUE, dependson='read-files'}
f <- data.frame(xwan[,1:2, with=FALSE])
rownames(f) <- f$PROBE_ID
eset_no_norm <- new("ExpressionSet", exprs=exprs_no_norm)
```

## Quantile normalization
```{r lumi-normalization, cache=TRUE, dependson='eset-creation'}
eset_normalized <- lumiN(eset_no_norm)
exprs_normalized <- log2(exprs(eset_normalized))
```

## features_2_genes
```{r feature2gene, cache=TRUE, dependson="all"}
f2g <- data.frame(xwan[, list(PROBE_ID, SYMBOL)])
rownames(f2g) <- f2g$PROBE_ID
colnames(f2g) <- c("feature_id", "gene_symbol")
```

## Store the expression matrices in the file system
```{r write-files, eval=TRUE}
write.table(exprs_normalized, file=paste(labkey.file.root, "analysis", "exprs_matrices", "exprs_matrix_normalized.tsv", sep="/"), sep="\t", quote=FALSE)
#write.table(exprs_norm, file=paste(labkey.file.root, "analysis", "exprs_matrices", "exprs_matrix_normalized.tsv", sep="/"), sep="\t", quote=FALSE)
write.table(f2g, file=paste(labkey.file.root, "analysis", "features2genes", "features_2_genes_HumanHT-12v4.tsv", sep="/"), sep="\t", quote=FALSE)
```
