```{r knitr-options, echo=FALSE, eval=TRUE, cache=FALSE}
library(knitr)
opts_knit$set(progress = TRUE, verbose = TRUE)
opts_chunk$set(cache=TRUE, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE, error=TRUE, dev="png", fig.width=6, fig.height=4, dpi=100, autodep=FALSE)
options(width=80)
```

```{r load-required-packages, cache=FALSE}
# Required librairies
library(Rlabkey)
library(rentrez)
```

```{r }
study_acc <- gsub(".*/", "", gsub("/@files", "", labkey.file.root))

dat <- labkey.data
ds_pubmed <- dat[dat$study_accession == study_acc, ]
```

```{r get-pubmed-info, cache.extra=format(Sys.time(),'%Y-%m-%H')}
# Update every month
get_reference <- function(id)
  {
  x <- entrez_summary(db="pubmed", id=id)
  reference <- paste(paste(x$AuthorList,collapse=", "), ". ", x$Title, " *", x$Source, "* ", x$Volume, "(", x$Issue, "), ", x$PubDate, ".", sep="")
  pubmed_link <- paste0("<a href='http://www.ncbi.nlm.nih.gov/pubmed/", id,"' target='_blank'>", "PMID:", id,"</a>")
  paste(reference, pubmed_link)
  }
pubmed_list <- entrez_link(db="all", id=ds_pubmed$pubmed_id, dbfrom="pubmed")
study_citation <- get_reference(ds_pubmed$pubmed_id)
url_citedin <- paste0("http://www.ncbi.nlm.nih.gov/pubmed?linkname=pubmed_pubmed_citedin&from_uid=", ds_pubmed$pubmed_id)
```
The above study is based on the following article(s): 



* `r study_citation`

The article has <a href=`r url_citedin` target="_blank">`r length(pubmed_list$pubmed_pubmed_citedin)` citations</a> in pubmed central. 

### Related articles in PubMed are listed below:

```{r list-related-articles, results='asis', dependson="get-pubmed-info"}
res <- lapply(pubmed_list$pubmed_pubmed[-1][1:5], get_reference)
for(i in 1:5)
  {
  cat(paste0(i,". ", res[i],"\n"))
  }
url_related <- paste0("http://www.ncbi.nlm.nih.gov/pubmed?linkname=pubmed_pubmed&from_uid=", ds_pubmed$pubmed_id)
```
Click <a href=`r url_related` target="_blank">here</a> for more suggestions.
