```{r knitr-opts, echo = FALSE, message = FALSE}
opts_chunk$set(echo = TRUE, message = FALSE)
opts_chunk$set(cache = FALSE, cache.path = file.path(labkey.file.root, "cache/Heatmap/"))
```

```{r libraries, echo = FALSE, message = FALSE}
library(pheatmap)
library(Biobase)
library(gplots)
library(data.table)
library(ImmuneSpaceR)
library(RColorBrewer)
```

```{r functions, echo = FALSE}
getRunFromCohort <- function(con, cohort){
  run <- gsub(".tsv$", "", unique(subset(con$data_cache$GE_inputs, arm_name == cohort)[, "name"]))
  return(run)
}
getUniqueGenes <- function(data){
   ugenes <- as.character(unique(data[!is.na(gene_symbol) & gene_symbol != "NA", gene_symbol]))
   ugenes <- unique(sapply(strsplit(ugenes, " /// "), "[[", 1)) # This is needed until we standardize the gene_names
}
```

```{r read-Data}
data <- data.table(labkey.data)
ugenes <- getUniqueGenes(data)
if(length(ugenes) > 50){
  data_ss <- data[order(p_value)][1:50]
  ugenes <- getUniqueGenes(data_ss)
  data <- data[gene_symbol %in% ugenes]
  warning("You have selected more than 50 unique genes. The heatmap will only show the top 50 selected genes with the lowest p_value. Try adding filters in the data tab to decrease the number of selected genes.")
}
uarm <- unique(data$analysis_accession_arm_name)
contrast <- "study_time_collected"
```

```{r checks}
errorString <- ""
if(nrow(data) ==0){
  errorString <- "ERROR: No genes have been selected. Try using different filtering criteria."
}
```
`r errorString`

```{r stop}
if(errorString != ""){
  opts_chunk$set(eval = FALSE, echo = FALSE)
}
```


```{r read-EM}
con <- CreateConnection()
runs <- getRunFromCohort(con, uarm)
```
```{r prints, eval = TRUE}
con
runs
```

```{r runs}
anno_list <- mat_list <- vector("list", length(runs))
for(runIdx in 1:length(runs)){
   EM <- con$getGEMatrix(runs[runIdx], summary = TRUE)
   pd <- data.table(pData(EM))
   pd <- pd[order(get(contrast), subject_accession)]
   coefs <- unique(pd[, get(contrast)])
   subs <- pd[, .N, by = subject_accession][N == length(coefs), subject_accession]
   pd <- pd[ subject_accession %in% subs]
   
   anno <- data.frame(pd[, c(contrast, "arm_name"), with = FALSE])
   rownames(anno) <- pd[, biosample_accession]

   exprs <- exprs(EM[ugenes, pd$biosample_accession])

   # If RNA-seq, let's transform the data via voom
   if(max(exprs)>100)
     exprs <- voom(EM[ugenes, pd$biosample_accession])$E
   
   mat <- exprs
   #mat <- matrix(0, nrow = nrow(exprs), ncol = length(coefs), dimnames = list(rownames(exprs), rownames(anno)))
   #for(i in 1:length(coefs)){
   #  mat[, i] <- rowMeans( exprs[, pd[ get(contrast) == coefs[i], biosample_accession]])   
   #}
   mat_list[[runIdx]] <- mat
   anno_list[[runIdx]] <- anno
}
matrix <- do.call("cbind", mat_list)
anno <- do.call("rbind", anno_list)
anno[, contrast] <- as.factor(anno[, contrast])
all_coefs <- unique(anno[, contrast])
```


```{r pheatmap, fig.align = "center", fig.height = 6, fig.width = 12}
#palette <- rev(brewer.pal(name="PiYG", n=11))
palette <- ISpalette(20)
#coefs_palette <- brewer.pal(name = "Greys", n = length(coefs))
coefs_palette <- colorpanel(n = length(all_coefs), low = "white", high = "black")
# Colors
anno_color <- list(coefs_palette)
names(anno_color)[[1]] <- contrast
names(anno_color[[1]]) <- all_coefs
#max <- max(matrix)
show_rnames <- ifelse(nrow(matrix) > 40, FALSE, TRUE)
clust_rows <- ifelse(nrow(matrix) < 2, FALSE, TRUE)
pheatmap(matrix, cluster_cols = FALSE, cluster_rows = clust_rows, scale = "row", 
         show_rownames = show_rnames, show_colnames = FALSE, 
         color = palette, annotation = anno, fontsize = 12, annotation_color = anno_color)
```
