#!/bin/bash

if [ `hostname | tail -c7` != 'rserve' ];then # RServe machine
    echo "This script should be executed on the RServe machine."
    exit 1
fi

if [ `whoami` != 'root' ] ; then
    echo 'You must be the root user in order to run this script'
    exit 1
fi

if [ $1 ] ; then
    VERSION=$1
else
    echo 'R version in the format X.Y.Z must be specified as the first argument'
    exit 1
fi

if [ ! -e `which git` ] ; then
    apt-get install git
fi
if [ ! -d /share/github/docker-rstudio ] ; then
    pushd /share/github
    echo
    echo '============================='
    echo 'Downloading the LabKey docker'
    echo '============================='
    git clone https://github.com/LabKey/docker-rstudio.git
    popd
else
    pushd /share/github/docker-rstudio
    git pull
    popd
fi
pushd /share/github/docker-rstudio/images/labkey/rstudio-base
docker pull rocker/rstudio:${VERSION}
./make ${VERSION}
popd

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
${DIR}/getRpkgs.sh

if [ $2 ] ; then
    BUILD_TYPE=$2
elif [ `hostname | head -c10` = 'immunetest' ] ; then
    BUILD_TYPE=dev
elif [ `hostname | head -c10` = 'immuneprod' ] ; then
    BUILD_TYPE=master
else
    echo 'Build type cannot be detected, must be specified as the second parameter'
    exit 1
fi
START_TIME=$SECONDS
docker build --no-cache -t immunespace/rstudio:${VERSION} --build-arg version=${VERSION} --build-arg build_type=${BUILD_TYPE} ${DIR}

ELAPSED_TIME=$(($SECONDS - $START_TIME))
echo
echo 'Completed in' `date -d "1970-01-01 ${ELAPSED_TIME} sec" +'%k:%M:%S'`

