# Creation of raw and normalized expression matrices from raw data.

### Report generated by `r labkey.user.email`

```{r knitr-opts, echo=FALSE}
opts_chunk$set(echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE, error=TRUE)
options(width=80)
```

```{r libraries}
library(data.table)
library(Rlabkey)
library(lumi)
```

```{r load-GE_files}

GE_files <- data.table(labkey.selectRows(labkey.url.base, labkey.url.path,
                        "study", "gene_expression_files", colNameOpt="rname"))
```

```{r read-files}
GE_files <- GE_files[file_info_name=="Whole Blood Microarray.txt"]
file <- paste(labkey.file.root, "rawdata/gene_expression", unique(GE_files$file_info_name), sep="/")
mat <- fread(file)
```

```{r change-colnames}
mat <- mat[, c("PROBE_ID", "SYMBOL", colnames(mat)[grep("Signal", colnames(mat))]), with=FALSE]
setnames(mat,colnames(mat),  gsub(".AVG.*$", "", colnames(mat)))
setnames(mat, colnames(mat), c("feature_id", "gene_symbol", na.omit(GE_files[match(colnames(mat), subject_accession), biosample_accession])))

```

```{r make-eset}
fdata <- mat[, list(feature_id, gene_symbol)]
rownames(fdata) <- fdata[, feature_id]
exprs <- as.matrix(mat[, 3:ncol(mat), with=FALSE])
rownames(exprs) <- mat[, feature_id]
eset <- new("ExpressionSet", exprs = exprs)
```

```{r normalize}
eset <- lumiN(eset, method="quantile")
exprs_normalized <- log2(exprs(eset))
exprs_normalized <- cbind(mat[, feature_id], exprs_normalized)
colnames(exprs_normalized)[1] <- "feature_id"
```

## Store the expression matrix as flat files
```{r write}
EM_name <- "whole_blood_baseline_normalized.tsv"
write.table(exprs_normalized, file = paste(labkey.file.root, "analysis/exprs_matrices", EM_name, sep="/"), sep="\t", quote=FALSE, row.names=FALSE)
```
