```{r knitr-opts, echo = FALSE}
library(knitr)
opts_chunk$set(message = FALSE, echo = FALSE, warning=FALSE)
opts_chunk$set(cache = FALSE, cache.path = file.path(labkey.file.root, "cache/GeneSetEnrichmentAnalysis/", labkey.user.email, ""))
```

```{r lib, cache = FALSE, message = FALSE, echo = FALSE}
library(Rlabkey)
library(ImmuneSpaceR)
library(UpdateAnno)
library(Biobase)
library(limma)
library(pheatmap)
library(reshape2)
library(gplots)
library(gtools)
library(data.table)
library(digest)
library(heatmaply)
library(DT)
```


```{r functions, echo = FALSE, cache = TRUE}
msig_rnames <- function(rnames){
  rnames <- paste0('<a href="http://www.broadinstitute.org/gsea/msigdb/cards/',
                   rnames, '.html" target="_blank">', rnames, '</a>')
  return(rnames)
}
emory_rnames <- function(rnames){
#  modules <- gsub("\\)$", "", gsub("^.*\\(", "", rnames))
#  rnames <- paste0('<a href="http://www.interactivefigures.com/meni/btm416_annotation/btmdata/',
#                   modules, '.htm" target="_blank">', rnames, '</a>')
  return(rnames)
}
baylor_rnames <- function(rnames){
  rnames <- paste0('<a href="http://www.biir.net/public_wikis/module_annotation/V2_Trial_8_Modules_',
                   gsub("_.*$", "", rnames), '" target="_blank">', rnames, '</a>')
  return(rnames)
}
format_table <- function(x, ...){
  require(knitr)
  require(data.table)
  if(!is(x,"data.table"))
    {
    # This is to make sure that we don't have issues with row names in data.frames
    stop("This function only works on data.tables")
    }
  out <- kable(x, "html", table.attr = 'class="display" id="res_table_GSEA"', escape = FALSE, output = FALSE, ...)
  footer <- paste0("</thead>\n<tfoot>", strsplit(strsplit(out,"<thead>")[[1]][2],"</thead>")[[1]][1], "</tfoot>\n")
  out_new <- gsub("</thead>",footer,out)
  cat(out_new)
}
```

```{r DataFinder-cache, cache = FALSE}
cached_pids <- labkey.selectRows(
    baseUrl = labkey.url.base, folderPath = labkey.url.path,
    schemaName = "study", queryName = "demographics", viewName="",
    colFilter=NULL, containerFilter=NULL, colNameOpt = "rname")$participantid
```

```{r connection, cache = TRUE, dependson="functions", cache.extra=digest(cached_pids)}
# When the list of patient_ids change, recreate the connection
con <- CreateConnection()
```

```{r params, cache = FALSE}
cohort <- labkey.url.params$cohort
set <- labkey.url.params$signature
contrast <- "study_time_collected"
```

```{r cache-cohort, cache = TRUE, cache.extra=cohort, dependson="connection"}
# When the cohort changes, we need to re-download the EM
EM <- con$getGEMatrix(cohort = cohort)
```
```{r cache-modules, cache = TRUE, cache.extra=set, dependson="connection"}
# When the modules/set changes, we need to re-assign these values
switch(set,
          `MSigDB c7` = {data(msigdb_immunologic_signatures);
                         gene_sets <- msigdb_immunologic_signatures;
                         func_rnames <- msig_rnames},
          `Blood transcription` = {data(emory_blood_transcript_modules);
                                gene_sets <- emory_blood_transcript_modules;
                                func_rnames <- emory_rnames},
          `G2 (Trial 8) Modules` = {data(chaussabel_modules);
                      gene_sets <- chaussabel_modules;
                      func_rnames <- baylor_rnames})
```

```{r camera, cache = TRUE, dependson="cache-cohort;cache-modules"}
indices <- ids2indices(gene_sets, fData(EM)$gene_symbol)
pData(EM)[, contrast] <- as.factor(pData(EM)[, contrast])
mm <- model.matrix(formula(paste("~participant_id +", contrast)), EM)
colnames(mm) <- make.names(colnames(mm))
```

## Gene set enrichment analysis of `r cohort`

```{r byDay,  cache = TRUE, dependson="camera", echo = FALSE}
lev <- levels(pData(EM)[, contrast])
lev_label <- paste0(contrast, lev[2:length(lev)])
lev <- make.names(lev_label)
cam_list <- vector('list', length = length(lev))
for(i in 1:length(lev)){
  contrasti <- lev[[i]]
    # Check if it's RNA-seq or microarrays
  if(max(Biobase::exprs(EM))>100)
    res <- camera(voom(EM), index = indices, design = mm, contrast = makeContrasts(contrasti, levels=mm), allow.neg.cor = TRUE, inter.gene.cor = NULL)
  else
    res <- camera(EM, index = indices, design = mm, contrast = makeContrasts(contrasti, levels=mm), allow.neg.cor = TRUE, inter.gene.cor = NULL)

  dt <- data.table(res) 
  dt[, Module := rownames(res)]
  dt[, Coefficient := lev_label[[i]]]
  dt[, PValue := ifelse(Direction=="Up", -10*log10(PValue), 10*log10(PValue))]
  cam_list[[i]] <- dt
}
table <- rbindlist(cam_list)
setcolorder(table, c("Module", "Coefficient", "NGenes", "Correlation", "Direction", "PValue", "FDR"))
table <- table[order(abs(PValue), decreasing = TRUE)]
if(contrast == "study_time_collected"){
 table <- table[, Coefficient := gsub(contrast, "Day ", table[, Coefficient])]
 table <- table[mixedorder(Coefficient)]
}
```

```{r heatmap-matrix, cache = TRUE, dependson="byDay"}
PValThresh <- 30
palette <- colorpanel(20, low = "#268bd2", mid = "#fdf6e3", high = "#dc322f")
DEM <- unique(table[abs(PValue)>PValThresh, Module])
if(length(DEM) > 20){
    DEM <- table[1:20, Module]
}

draw_heatmap <- FALSE
infostring <- ""
if(length(DEM) > 0){
  DEM <- table[Module %in% DEM, list(Module, Coefficient, PValue)]
  DEM <- dcast(DEM, formula = Module ~ Coefficient, value.var = "PValue")[, c("Module", mixedsort(unique(table$Coefficient))), with = FALSE]
  mat <- as.matrix(DEM[, 2:ncol(DEM), with = FALSE])
  rownames(mat) <- DEM$Module
  draw_heatmap <- TRUE
} else{
  infostring <- "No gene set were found to be enriched."
}
```


```{r kable, cache = TRUE, dependson="byDay"}
table <- table[, Module := func_rnames(Module)]
table <- table[, PValue := abs(PValue)]
setnames(table, "PValue", "10log10(p)")
#format_table(table)
datatable(table, escape = 1)
```

<div align='center'>
```{r pheatmap, cache=TRUE, dependson="heatmap-matrix", fig.width=15, fig.align = "center"}
if(draw_heatmap){
  max <- max(abs(mat))
  if(nrow(mat) > 0){
    mat2 <- mat
    rownames(mat) <- ifelse(nchar(rownames(mat))>15, paste(substr(rownames(mat), 1, 12),
                     substr(rownames(mat), nchar(rownames(mat))-10, nchar(rownames(mat))), sep =" ... "),
                     rownames(mat))
    clust_rows <- ifelse(nrow(mat) < 2, FALSE, TRUE)
    #pheatmap(mat, cluster_cols = FALSE, cluster_rows = clust_rows, fontsize = 12,
    #  breaks = seq(-max, max, length.out = length(palette)+1), color = palette)
    heatmaply(x = mat2, dendrogram = ifelse(nrow(mat2) >= 2, "row", "none"), colors = palette)
  }
}
```
</div>

`r infostring`
