```{r knitr-opts, echo = FALSE}
library(knitr)
opts_chunk$set(message = FALSE, echo = FALSE, warning = FALSE)
opts_chunk$set(cache = FALSE, cache.path = file.path(labkey.file.root, "cache/GeneExpressionExplorer/", labkey.user.email, ""))
```

```{r setup}
suppressMessages(library(Cairo))
suppressMessages(library(RJSONIO))
library(ggplot2)
library(Biobase)
library(data.table)
library(Rlabkey)
library(ImmuneSpaceR)
library(reshape2)
library(limma)
library(plotly)

stopcheck <- function(data) {
  stop(paste0(paste(capture.output(str(data)), collapse="\n"), "\nl.u.b: ",labkey.url.base, "\nl.u.p: ",labkey.url.path))
}

imageWidth <- as.numeric(labkey.url.params$imageWidth)
imageHeight <- as.numeric(labkey.url.params$imageHeight)

# Input parameters
response <- as.character(labkey.url.params$response)
ems <- RJSONIO::fromJSON(labkey.url.params$ema)
input_cohorts <- RJSONIO::fromJSON(labkey.url.params$cohorts)
input_genes <- RJSONIO::fromJSON(labkey.url.params$genes)
timePoint <- as.numeric(labkey.url.params$timePoint)
timePointUnit <- as.character(labkey.url.params$timePointUnit)
normalize <- as.logical(labkey.url.params$normalize)
interactive <- as.logical(labkey.url.params$interactive)

# Data grid
filters <- RJSONIO::fromJSON(labkey.url.params$filters)

# Additional options
textSize <- as.numeric(labkey.url.params$textSize)
facet <- tolower(labkey.url.params$facet)
shape <- tolower(labkey.url.params$shape)
color <- tolower(labkey.url.params$color)
size <- tolower(labkey.url.params$size)
alpha <- tolower(labkey.url.params$alpha)

#stopcheck(labkey.url.params)

# helper functions
add_r2 <- function(data) {
  dt <- data.table(data)
  dt <- dt[, r2 := paste("R^2 ==", round(summary(lm(response ~ value))[['r.squared']], 3)), by = "cohort,gene_symbol"]
  dt <- dt[, r2x := (min(value) + max(value)) / 2, by = "cohort,gene_symbol"]
  dt <- dt[, r2y := max(response), by = "cohort,gene_symbol"]
  return(data.frame(dt))
}

check_cohorts <- function(data) {
  # Add study_accession information to the cohorts that are shared accross studies
  dt <- data.table(data)
  dt <- dt[, study_accession := paste0("SDY", gsub("^.*\\.", "", participant_id))]
  uc <- unique(dt[, study_accession, by ="cohort"])[, .N, by = "cohort"][N >1, cohort]
  dt[cohort == uc, cohort := paste0(cohort, " (", study_accession, ")")]
  return(data.frame(dt))
}

parseFilter <- function(e) {
  paste0(URLencode(e['fieldKey']), '~', e['op'], '=', URLencode(e['value']))
}

# Ensure Rlabkey format of vector of filter strings
if( length(filters) > 0 ){
  filtChk <- colFilter <- unlist(lapply(filters, parseFilter))
}else{
  colFilter <- NULL
  filtChk <- "" # Need non-NULL str for reload logic
}

# Reload everything when DataFinder filters are updated
if( !exists("con") || !all(loaded_filter == filtChk) ){
  con <- CreateConnection()
  if(exists("loaded_ems")) rm(loaded_ems)
  if(exists("loaded_genes")) rm(loaded_genes)
}

# Re-download EM and demographics when the selected cohorts change
if(!exists("loaded_ems") || length(loaded_ems) != length(input_cohorts) || !all(loaded_ems %in% ems)) {
  EM <- con$getGEMatrix(matrixName = ems, reload = TRUE)
  if(any(exprs(EM)>100, na.rm = TRUE)) {
    dt <- data.table(voom(EM)$E)
    dt <- dt[, gene_symbol := rownames(exprs(EM))]
  } else {
    dt <- data.table(exprs(EM))
    dt <- dt[, gene_symbol := rownames(exprs(EM))]
  }
  DEMO <- unique(con$getDataset("demographics")[, list(participant_id, age_reported, gender, race)])
  setnames(DEMO, "age_reported", "age")
}

HAI <- con$getDataset("hai", original_view = TRUE, colFilter = colFilter, reload = TRUE)
HAI <- HAI[, list(arm_accession, study_time_collected, study_time_collected_unit,
                  response = value_reported / mean(value_reported[study_time_collected <= 0])), by = "virus,participant_id"]
# HAI at peak immunogenicity
HAI <- HAI[, mr := mean(response), by = "study_time_collected"]
HAI <- HAI[, ma := max(mr), by = "arm_accession"]
peak <- unique(HAI[mr == ma, list(study_time_collected, arm_accession)])
HAI <- merge(HAI, peak, by = c("study_time_collected", "arm_accession"))
HAI <- HAI[, list(response = log2(max(response))), by = "participant_id"]

PD <- data.table(pData(EM))
PD <- merge(PD, HAI, by = "participant_id")

# Fail gracefully if PD empty due to non-overlap in participant ids, issue num 21
if( nrow(PD) == 0 ){
  stop("Participant IDs in the requested HAI dataset do not overlap with those in the requested pheno data. Please select a different cohort or timepoint and try again.")
}

PD <- merge(PD, DEMO, by = "participant_id")
#EM <- EM[, pData(EM)$biosample_accession %in% PD$biosample_accession]
dt <- dt[, c("gene_symbol", PD$biosample_accession), with = FALSE]


# Subset
#ssEM <- EM[input_genes, ]
#data <- data.table(melt(exprs(ssEM), varnames = c("gene_symbol", "biosample_accession")))
ssdt <- dt[gene_symbol %in% input_genes, ]
data <- melt(ssdt, variable.name = "biosample_accession", id.vars = "gene_symbol")
data <- merge(data, PD, by = "biosample_accession")
if(normalize) {
  data[, value := value[study_time_collected == timePoint & tolower(study_time_collected_unit) == timePointUnit]  -
                  value[study_time_collected == 0 & tolower(study_time_collected_unit) == timePointUnit],
        by = "participant_id,gene_symbol"]
  xlab <- "log expression normalized to baseline"
} else {
  xlab <- "log expression"
}
data <- data[study_time_collected == timePoint & tolower(study_time_collected_unit) == timePointUnit]
data <- add_r2(data)
data <- check_cohorts(data)

# Plot
if(color == "") color <- NULL
if(shape == "") shape <- NULL
if(size == "") size <- NULL
if(alpha == "") alpha <- NULL
```

<div align = 'center'>
```{r visualization, fig.width = 12, fig.height = 10}
p <- ggplot(data = data, aes(x = value, y = response)) +
  geom_point(aes_string(size = size, color = color, alpha = alpha, shape = shape)) +
  geom_smooth(method = "lm") +
  ylab(response) +
  xlab(xlab) +
  geom_text(aes(x = r2x, y = r2y, label = r2), hjust = 0, vjust = 1, data = data, parse = TRUE) +
  theme_IS(base_size = textSize) # theme(text = element_text(size = textSize))
if(facet == "grid") {
  p <- p + facet_grid(aes(cohort, gene_symbol), scales = "free")
} else{
  p <- p + facet_wrap(~cohort + gene_symbol, scales = "free")
}

if (interactive) {
  ggplotly(p)
} else {
  CairoPNG(filename = "${imgout:Plot.png}", width = imageWidth, height = imageHeight)
  print(p)
  dev.off()
}

# Variables used for caching
loaded_ems <- ems
loaded_genes <- input_genes
loaded_filter <- filtChk
```
</div>
