# Heatmap of differentially expressed genes in LAIV 2008/2009
### Report generated by `r labkey.user.email`

```{r knitr-options, echo=FALSE, eval=TRUE, cache=FALSE}
library(knitr)
opts_knit$set(progress = TRUE, verbose = TRUE)
opts_chunk$set(cache=TRUE, echo=FALSE, eval=TRUE, message=FALSE, error=TRUE, dev="png", fig.width=10, fig.height=8, dpi=120, fig.align="center")
options(width=80)
```

```{r load-required-packages, cache=FALSE}
library(Biobase)
library(Rlabkey)
library(data.table)
library(pheatmap)
library(RColorBrewer)
```

```{r global-options, cache=FALSE}
# Colorblind Safe!
# Palette for heatmaps
mypalette <- rev(brewer.pal(name="PiYG", n=11))
```

## Summary

In this report, we generate a heatmap of differentially expressed genes detected by <a href="http://www.bioconductor.org/packages/2.12/bioc/html/limma.html" target="_blank">Limma</a> comparing all time points to baseline.
<br />

## Results

```{r read-analysis, cache.extra=digest::digest(labkey.data)}
gea <- labkey.data
```

```{r expression, dependson="read-analysis"}
exMat <- labkey.selectRows(baseUrl =labkey.url.base, folderPath = labkey.url.path, schemaName = "study", queryName = "gene_expression_matrices", colFilter=makeFilter( c( 'expression_matrix_accession', 'IN', "EXPM0002") ), colNameOpt="rname")
# Only keep data that have all timepoints
exMat <- data.table(exMat)
exMat <- exMat[,keep:=(sum(study_time_reported%in%c(0,3,7))==3),by="biosample_accession_name,subject_accession"]
exMat <- exMat[keep==TRUE]
exMat <- data.frame(exMat[matrix_description_description%like%"LAIV"])
exMatLink <- paste(labkey.file.root, "analysis/exprs_matrices", unique(exMat$file_info_name), sep="/")
exprs <- read.table(exMatLink)
```

```{r fdata, cache=TRUE, dependson="expression"}
fdLink <- paste(labkey.file.root, "analysis/features2genes", unique(exMat$feature_mapping_file), sep="/")
fdata <- read.table(fdLink, header=TRUE)
fdata <- fdata[na.omit(match(rownames(exprs), fdata$feature_id)), ]
```

```{r pdata, cache=TRUE, dependson="expression"}
# Query expression matrix
rownames(exMat) <- exMat$biosample_accession
exMat$study_time_reported <- as.character(exMat$study_time_reported)
exMat <- exMat[na.omit(match(colnames(exprs), exMat$biosample_accession)),]
```

```{r eset, cache=TRUE, dependson="expression;fdata;pdata"}
exprs <- exprs[, rownames(exMat)]
eset <- ExpressionSet(assayData = as.matrix(exprs), phenoData = as(exMat, "AnnotatedDataFrame"), featureData = as(fdata, "AnnotatedDataFrame"))
```

```{r filtering, dependson="read-analysis"}
DEP <- as.character(unique(gea$feature_id))
```

`r length(DEP)` differentially expressed probes have been selected.

```{r heatmap, warning=FALSE, dependson="filtering"}
sseset <- eset[DEP,eset$study_time_reported %in% c("0","3","7")]
sseset <- sseset[,order(sseset$study_time_reported)]
t <- sseset$study_time_reported
FC <- cbind(exprs(sseset[,t==3]) - exprs(sseset[,t==0]), exprs(sseset[,t==7]) - exprs(sseset[,t==0]))
show_rownames <- FALSE
if(nrow(FC) < 100){
	rownames(FC) <- substr(paste0(rownames(FC), "_(", fdata[rownames(FC), "gene_symbol"], ")"),1,30)
    show_rownames <- TRUE
}
t <- t[t!=0]
colnames(FC) <- paste(sseset[,sseset$study_time_reported %in% t]$subject_accession, t, sep="_")
   
anno <- data.frame(time=t)
rownames(anno) <- colnames(FC)
pheatmap(FC, color=mypalette, annotation=anno, cluster_cols=FALSE, show_colnames=FALSE, show_rownames=show_rownames, breaks = seq(-3, 3, length.out = length(mypalette) + 1), fontsize = 8, fonsize_row=2)
```
